// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHQgToxJ0jRFaKfsmRnVdWej1EwU5KJ74',
    appId: '1:471255770476:web:6828a8cfccfdf7cb7f7f49',
    messagingSenderId: '471255770476',
    projectId: 'yogabliss-2cb54',
    authDomain: 'yogabliss-2cb54.firebaseapp.com',
    storageBucket: 'yogabliss-2cb54.firebasestorage.app',
    measurementId: 'G-PYPLDNKTZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbnTI0sbk6O957e5cTBCbMYEZq4zfIQt8',
    appId: '1:471255770476:android:110d87a744fec2907f7f49',
    messagingSenderId: '471255770476',
    projectId: 'yogabliss-2cb54',
    storageBucket: 'yogabliss-2cb54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHJbFP3Tj4qhqrwqtY3BQWPTYBHadLwgM',
    appId: '1:471255770476:ios:286ca513154a9a627f7f49',
    messagingSenderId: '471255770476',
    projectId: 'yogabliss-2cb54',
    storageBucket: 'yogabliss-2cb54.firebasestorage.app',
    iosBundleId: 'com.example.yoga',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHJbFP3Tj4qhqrwqtY3BQWPTYBHadLwgM',
    appId: '1:471255770476:ios:286ca513154a9a627f7f49',
    messagingSenderId: '471255770476',
    projectId: 'yogabliss-2cb54',
    storageBucket: 'yogabliss-2cb54.firebasestorage.app',
    iosBundleId: 'com.example.yoga',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHQgToxJ0jRFaKfsmRnVdWej1EwU5KJ74',
    appId: '1:471255770476:web:f01cdf834588c5a17f7f49',
    messagingSenderId: '471255770476',
    projectId: 'yogabliss-2cb54',
    authDomain: 'yogabliss-2cb54.firebaseapp.com',
    storageBucket: 'yogabliss-2cb54.firebasestorage.app',
    measurementId: 'G-CX1E2H3SKL',
  );
}
